[package]
name = "reshotka"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
csv = "1.3.1"
nalgebra = "0.33.0"
num = "0.4.3"
rand = "0.8.5"
rayon = "1.10.0"
roots = "0.0.8"
serde = { version = "1.0.217", features = ["derive"] }
varpro = "0.11.0"
