[package]
name = "reshotka"
version = "0.1.0"
edition = "2021"

# [[bin]]
# name = "parse_hmc"
# path = "src/parse_hmc.rs"


[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
nalgebra = "0.33.0"
num = "0.4.3"
rand = "0.8.5"
rayon = "1.10.0"
roots = "0.0.8"
varpro = "0.10.0"
